parameters:
  - name: webAppName
    type: string

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'dist'
      skip_app_build: true
    env:
      azure_static_web_Apps_api_token: $(swa_token)