trigger:
  branches:
    include:
      - Development

pr: none

pool:
  vmImage: ubuntu-20.04

steps:
  - template: templates/build.yml
  - template: templates/deploy.yml
    parameters:
      webAppName: 'app-autrnewclient-dev-ase-01'
