trigger:
  branches:
    include:
      - Development

pr: none

pool:
  vmImage: ubuntu-latest
jobs:
- job: 'Build and Deploy'
  steps:
  - template: templates/build.yml
  - template: templates/deploy.yml
    parameters:
      webAppName: 'app-autrnewclient-dev-ase-01'
