name: Build

on:
  pull_request:
    branches: [ Development, UAT, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          echo "" >> .env
          echo "VITE_AT_CLIENT_ID=client_id" >> .env
          echo "VITE_AT_TENANT_ID=tenant_id" >> .env
          echo "VITE_API_SCOPE=api_scope" >> .env
          echo "VITE_REACT_API_URL=https://localhost:5001" >> .env
      - run: npm ci
      - run: npm run build